import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./home/CompoPage1/NavBar"; // تأكد من تعديل المسار إذا لزم الأمر
import Fotter from "./home/CompoPage1/Fotter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food Recipes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar /> 
        <main style={{ minHeight: 'calc(100vh - 100px)' }}> 
          {children}
        </main>
        <Fotter />
      </body>
    </html>
  );
}
